package(default_visibility = ["//visibility:public"])

java_binary(
    name = "server",
    srcs = [
        "HelloServer.java",
        "MyHandler.java"
    ],
    main_class = "codelab.rpc.http.java.HelloServer",
    deps = [
    ],
)