package(default_visibility = ["//visibility:public"])

alias(
    name = "file_utils_lib",
    actual = "//base/java/com/codelab/base/file:file_utils_lib",
    visibility = ["//visibility:public"],
)

alias(
    name = "proto_utils_lib",
    actual = "//base/java/com/codelab/base/protobuf:proto_utils_lib",
    visibility = ["//visibility:public"],
)